{
 "title": "eCAL Monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "hname",
    "query": "SELECT DISTINCT hname FROM processes"
   },
   {
    "name": "logs",
    "query": "SELECT DISTINCT level FROM logs"
   },
   {
    "name": "topic",
    "label": "topic",
    "query": "SELECT DISTINCT tname FROM current_topics"
   },
   {
    "name": "service",
    "query": "SELECT DISTINCT sname FROM current_services"
   }
  ]
 },
 "panels": [
  { "title": "System Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Interhost Traffic",
   "type": "nodeGraph",
   "description": "Nodegraph of all currently active hosts and their communication between each other",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "queryText": "SELECT \r\n    arc__ok,\r\n    arc__nok,\r\n    detail__hname,\r\n    detail__hgname,\r\n    detail__ram,\r\n    detail__disk,\r\n    detail__cpu,\r\n    id,\r\n    title,\r\n    subtitle,\r\n    mainstat,\r\n    color,\r\n    icon,\r\n    nodeRadius\r\nFROM \r\n    host_nodes;",
     "rawQueryText": "SELECT \r\n    arc__ok,\r\n    arc__nok,\r\n    detail__hname,\r\n    detail__hgname,\r\n    detail__ram,\r\n    detail__disk,\r\n    detail__cpu,\r\n    id,\r\n    title,\r\n    subtitle,\r\n    mainstat,\r\n    color,\r\n    icon,\r\n    nodeRadius\r\nFROM \r\n    host_nodes;"
    },
    { "queryText": "SELECT * From host_edges", "rawQueryText": "SELECT * From host_edges" }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "queryText": "SELECT *\nFROM logs\nWHERE level IN (${logs:sqlstring});\n",
     "rawQueryText": "SELECT *\nFROM logs\nWHERE level IN (${logs:sqlstring});\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Message Drops",
   "type": "barchart",
   "description": "Show the 5 subscribers receiving the most message drops.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "queryText": "SELECT hname, tname, direction, message_drops \nFROM current_topics \nWHERE direction = 'subscriber' \nORDER BY message_drops DESC \nLIMIT 5;\n",
     "rawQueryText": "SELECT hname, tname, direction, message_drops \nFROM current_topics \nWHERE direction = 'subscriber' \nORDER BY message_drops DESC \nLIMIT 5;\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Bandwidth Heatmap",
   "type": "bargauge",
   "description": "Show the 10 processes with the highest network usage in kbitps.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "Kbits" } },
   "targets": [
    {
     "queryText": "SELECT tname, direction, SUM(throughput)\nFROM current_topics\nGROUP BY pid, direction\nORDER BY throughput DESC, tname DESC;",
     "rawQueryText": "SELECT tname, direction, SUM(throughput)\nFROM current_topics\nGROUP BY pid, direction\nORDER BY throughput DESC, tname DESC;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "System Health Monitor",
   "type": "barchart",
   "description": "Shows the process severity of the 5 most severe processes",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "queryText": "SELECT uname, state_severity AS \"State Severity\" FROM current_processes\r\nORDER BY state_severity DESC, state_severity_level DESC",
     "rawQueryText": "SELECT uname, state_severity AS \"State Severity\" FROM current_processes\r\nORDER BY state_severity DESC, state_severity_level DESC",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Pub Sub Distribution",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT direction, COUNT(direction) as count \nFROM current_topics \nGROUP BY direction;",
     "rawQueryText": "SELECT direction, COUNT(direction) as count \nFROM current_topics \nGROUP BY direction;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Communication Layer Distribution",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT layer, COUNT(layer) as count \nFROM current_topics \nGROUP BY layer;",
     "rawQueryText": "SELECT layer, COUNT(layer) as count \nFROM current_topics \nGROUP BY layer;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  { "title": "Further Visualizations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Pub-Sub Graph for Topic ${topic}",
   "type": "nodeGraph",
   "description": "Nodegraph of all currently active topics and their communication between each other",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 32 },
   "repeat": "topic",
   "targets": [
    {
     "queryText": "SELECT * FROM pst_nodes\r\nWHERE secondarystat = '${topic}' \r\n",
     "rawQueryText": "SELECT * FROM pst_nodes\r\nWHERE secondarystat = '${topic}' \r\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    },
    {
     "queryText": "SELECT * FROM pst_edges\r\nWHERE target = 'TransferLanes' or source = 'TransferLanes'   ",
     "rawQueryText": "SELECT * FROM pst_edges\r\nWHERE target = '${topic}' or source = '${topic}'   ",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Client Server",
   "type": "nodeGraph",
   "description": "Nodegraph of a selected service and its clients.",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "queryText": "SELECT * FROM cs_nodes\r\nWHERE secondarystat =''\r\n",
     "rawQueryText": "SELECT * FROM cs_nodes\r\nWHERE secondarystat ='$service'\r\n"
    },
    {
     "queryText": "SELECT * From cs_edges\r\nWHERE secondarystat =''",
     "rawQueryText": "SELECT * From cs_edges\r\nWHERE secondarystat ='$service'"
    }
   ]
  },
  {
   "title": "Process Graph",
   "type": "nodeGraph",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 43 },
   "targets": [
    {
     "queryText": "SELECT * FROM process_nodes\n",
     "rawQueryText": "SELECT * FROM process_nodes\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    },
    {
     "queryText": "SELECT * FROM process_edges\n\n",
     "rawQueryText": "SELECT * FROM process_edges\n\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  }
 ]
}